# Generated by Django 4.2.20 on 2025-05-06 16:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='equipment_type',
            field=models.CharField(choices=[('tractor', 'Трактор'), ('combine', 'Комбайн'), ('seeder', 'Сеялка'), ('plow', 'Плуг')], default=django.utils.timezone.now, max_length=50, verbose_name='Тип техники'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='equipment/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='listing',
            name='power',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность (л.с.)'),
        ),
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Регион'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
    ]
