# Generated by Django 4.2.20 on 2025-05-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_equipment_type_listing_image_listing_power_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Instagram username'),
        ),
        migrations.AddField(
            model_name='listing',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='listing',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram username'),
        ),
    ]
