# Generated by Django 4.2.20 on 2025-05-13 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_instagram_username_listing_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='instagram_username',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50, verbose_name='Instagram username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='telegram_username',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=50, verbose_name='Telegram username'),
            preserve_default=False,
        ),
    ]
